<a href="https://colab.research.google.com/github/Anchihoon/Python-practice/blob/main/An%20python%206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np   #Numpy 패키지를 임포트 하는거 일반적으로 np라고 씀
ar = np.array(range(10))
print(ar)
type(ar) #ndarray 타입

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [ ]:
ar = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(len(ar))
print(len(ar[0])) #0번째 행의 열의 개수가 몇개인지 알려줌 인데스 번호를 넣으면 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3


In [ ]:
ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar #행,열,깊이까지 있는 3-D array임

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
import numpy as np
arrayA = np.zeros((3,6)) #행렬을 zero로 채우는 함수
arrayA 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
import numpy as np
arrayA=np.ones((3,6)) #행렬을 1로 채우는 함수
arrayA

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
ar0 = np.arange(100,110)
ar1 = np.arange(100,110).reshape(2,5)
print(ar0,'\n')
print(ar1)

[100 101 102 103 104 105 106 107 108 109] 

[[100 101 102 103 104]
 [105 106 107 108 109]]


In [ ]:
np.random.random((2,5,3))

array([[[0.20795377, 0.78913065, 0.69674132],
        [0.89547117, 0.85342749, 0.56538107],
        [0.46579781, 0.33425785, 0.45343808],
        [0.80281904, 0.92003664, 0.55713302],
        [0.3942839 , 0.26613073, 0.01793522]],

       [[0.32834778, 0.14841104, 0.77595993],
        [0.5577281 , 0.3620907 , 0.31466657],
        [0.4714489 , 0.34574611, 0.37227291],
        [0.50869587, 0.43995709, 0.50352676],
        [0.63589925, 0.83795625, 0.79348666]]])

In [ ]:
np.random.random((2,4))

array([[0.61769209, 0.12486374, 0.5693581 , 0.21086434],
       [0.26577199, 0.13661059, 0.52272829, 0.8669543 ]])

In [ ]:
np.random.uniform(3.5,6,(3,3))

array([[3.50911669, 3.56865021, 3.91950447],
       [5.01963568, 5.86438889, 5.1927058 ],
       [5.09846426, 5.79174921, 4.51047056]])

In [ ]:
np.random.randint(0,7,(2,3,4))

array([[[3, 0, 2, 1],
        [2, 5, 4, 1],
        [4, 0, 2, 4]],

       [[4, 2, 0, 5],
        [1, 3, 6, 2],
        [4, 3, 2, 6]]])

In [ ]:
np.random.randint(-5,5,7)

array([ 2,  3,  1, -4,  3, -2, -5])

In [ ]:
import numpy as np
a = np.linspace(0, 15, 4)
print(a)
b = np.linspace(0,1,5)
print(b)

[ 0.  5. 10. 15.]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a = np.arange(10).reshape(2,5)
print(a,'\n')
print(a.T)   #Transpose 시키는것

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
ar = np.arange(12).reshape(2,2,3)
print(ar,'\n')
print(ar[0],'\n')
print(ar[0][1],'\n')
print(ar[0,1,2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 

[[0 1 2]
 [3 4 5]] 

[3 4 5] 

5


In [ ]:
ar = np.arange(12).reshape(3,4)
print(ar[0:, 1:],'\n')
print(ar[1:, 1:],'\n')
print(ar[1:2,1:2])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]] 

[[ 5  6  7]
 [ 9 10 11]] 

[[5]]


In [ ]:
import numpy as np
ar0 = np.array([10, 8, 15, 7, 19])
print(ar0,'\n')
ar1 = np.arange(10,100,10).reshape(3,3)
print(ar1,'\n')
#ar2 = np.array([[[100,90,80],[70,60,50]],[[]]]) 뭐 이런식으로 만들면 됨

[10  8 15  7 19] 

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
ar = np.arange(10,25).reshape(3,5)
ar

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ar = np.arange(11,61).reshape(2,5,5)
ar

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [ ]:
ar = np.arange(74, 250, 5).reshape(3,3,4)
ar

array([[[ 74,  79,  84,  89],
        [ 94,  99, 104, 109],
        [114, 119, 124, 129]],

       [[134, 139, 144, 149],
        [154, 159, 164, 169],
        [174, 179, 184, 189]],

       [[194, 199, 204, 209],
        [214, 219, 224, 229],
        [234, 239, 244, 249]]])

In [ ]:
ar = np.ones((2,5,4,))
ar

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
ar = np.zeros((3,3,3))
ar

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
ar = np.random.random((5,5,2))
ar

array([[[0.44174361, 0.23100554],
        [0.51605676, 0.16829166],
        [0.83525799, 0.3516442 ],
        [0.6308635 , 0.78920303],
        [0.45686383, 0.07678585]],

       [[0.97479885, 0.85160476],
        [0.22479371, 0.48017056],
        [0.25731651, 0.91479592],
        [0.92185725, 0.59262145],
        [0.73801498, 0.37983054]],

       [[0.73296778, 0.88955775],
        [0.71794281, 0.34967265],
        [0.21042558, 0.07844734],
        [0.80312099, 0.58078283],
        [0.24107378, 0.93408183]],

       [[0.32303961, 0.74317385],
        [0.74888686, 0.29040651],
        [0.65114406, 0.57418352],
        [0.37602732, 0.1531619 ],
        [0.06281904, 0.17165595]],

       [[0.00162321, 0.7892185 ],
        [0.09165033, 0.12250115],
        [0.90705867, 0.95470418],
        [0.74524741, 0.32400809],
        [0.59137727, 0.20250718]]])

In [ ]:
ar = np.random.uniform(4.5,7,(7,1,4))
ar

array([[[5.12366618, 6.21065321, 5.26726089, 6.99154047]],

       [[5.19685306, 6.56814089, 5.67682222, 5.98527849]],

       [[4.99617917, 6.72144905, 6.55440668, 6.06998058]],

       [[6.78588179, 6.87725236, 4.82313383, 4.67621203]],

       [[4.60370004, 4.76433295, 6.43845815, 6.37158813]],

       [[6.35075114, 6.56404191, 6.91654132, 4.9111493 ]],

       [[6.28936098, 4.81705047, 4.83678544, 6.69520343]]])

In [ ]:
ar = np.linspace(110,120,5)
ar

array([110. , 112.5, 115. , 117.5, 120. ])

In [ ]:
ar = np.arange(0,27).reshape(3,9)
ar0 = ar.T # ar0 = np.transpose(ar) 로 해도 전치행렬된다.
ar0

array([[ 0,  9, 18],
       [ 1, 10, 19],
       [ 2, 11, 20],
       [ 3, 12, 21],
       [ 4, 13, 22],
       [ 5, 14, 23],
       [ 6, 15, 24],
       [ 7, 16, 25],
       [ 8, 17, 26]])

In [ ]:
ar = np.arange(15).reshape(3,5) #어떤형태가 나올지 예상하고 슬라이싱하는 연습을 해봐라
ar0 = ar[1:,1:]
print(ar,'\n')
print(ar0,'\n')
ar1 = ar[:2,:1]
print(ar1,'\n')
ar2 = ar[1:2, 3:]
print(ar2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 6  7  8  9]
 [11 12 13 14]] 

[[0]
 [5]] 

[[8 9]]


In [ ]:
ar = np.random.random((2,2,4))
print(ar,'\n')
print(np.min(ar[:1,]),'\n')
print(np.max(ar))

[[[0.28925519 0.83455945 0.6479253  0.29008643]
  [0.39733093 0.20675606 0.36199388 0.05870398]]

 [[0.16813195 0.34882375 0.75002423 0.41615126]
  [0.82612079 0.739028   0.71712565 0.09056938]]] 

0.05870397688067586 

0.8345594464484094


In [ ]:
ar = np.random.random((2,2,4))
print(ar,'\n')
print(np.argmin(ar),'\n')
np.argmax(ar)

[[[0.66161819 0.52401993 0.64474971 0.1279311 ]
  [0.17967589 0.84411612 0.90834332 0.12894254]]

 [[0.92356836 0.78584711 0.42160658 0.08036056]
  [0.06060646 0.63557129 0.55956921 0.18418349]]] 

12 



8

In [ ]:
ar = np.arange(1, 31, 2).reshape(3,5)
print(ar,'\n')
print(np.sum(ar),'\n')
print(np.mean(ar),'\n')
print(np.median(ar))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]] 

225 

15.0 

15.0


In [ ]:
ar = np.arange(1, 31, 2).reshape(3,5)
print(ar,'\n')
print(np.sum(ar, axis=0),'\n')
print(np.sum(ar, axis=1),'\n')
print(np.sum(ar, axis=0),'\n')
print(np.sum(ar[1:], axis=0))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]] 

[33 39 45 51 57] 

[ 25  75 125] 

[33 39 45 51 57] 

[32 36 40 44 48]


In [ ]:
ar = np.arange(1,15)
np.random.shuffle(ar)
print(ar,'\n')
print(np.sort(ar))

[ 7  4  5 11 10 12  6 13  9 14  3  1  2  8] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
ar = np.arange(1,16)
np.random.shuffle(ar)
ar = ar.reshape(3,5)
print(ar,'\n')
ar2= np.sort(ar)
print(ar2,'\n')
ar3 = np.sort(ar, axis=0)
print(ar3)

[[14 11  1 15 10]
 [ 9  3  7  2  4]
 [13  5  6 12  8]] 

[[ 1 10 11 14 15]
 [ 2  3  4  7  9]
 [ 5  6  8 12 13]] 

[[ 9  3  1  2  4]
 [13  5  6 12  8]
 [14 11  7 15 10]]


In [ ]:
ar = np.random.randint(-10,10,(2,5))
print(ar,'\n')
np.unique(ar)

[[ -6  -6  -6 -10  -7]
 [  5   2  -6   7  -6]] 



array([-10,  -7,  -6,   2,   5,   7])